# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'X_23.10.8753.32995'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'AutomationProjects/Windows/VB/SimpleLog_Windows_VB/project.json'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    runWorkflowAnalysis: true
    traceLevel: 'Information'