trigger: none
pr: none

# pr:
#   branches:
#     include:
#     - main

pool:
  vmImage: windows-latest

steps:
  - task: DownloadPackage@1
    inputs:
      packageType: 'nuget'
      feed: '03327aeb-cec9-448f-bdda-9ca558ee7f9c/3c9acfa8-aca5-4d13-b294-50fc18fd4611'
      view: '57750bdc-fc87-44d4-9588-f82ed5976e95'
      definition: '71500f34-1d0b-4e9a-a48f-d799316847ff'
      version: '23.4.8951.9936'
      extract: false
      downloadPath: '$(System.ArtifactsDirectory)'
  
  - task: UiPathInstallPlatform@4
    inputs:
      cliVersion: 'WIN_23.10.8894.39673'  # doesn't matter that here it's 23.10
      cliNupkgPath: '$(System.ArtifactsDirectory)/UiPath.CLI.Windows.nupkg'
  
  - task: UiPathPack@4
    inputs:
      versionType: 'AutoVersion'
      projectJsonPath: 'AutomationProjects/CrossPlatform/VB/TestCase_CrossPlatform_VB/project.json'
      outputPath: '$(Build.ArtifactStagingDirectory)\Output'
      traceLevel: 'Information'