trigger: none
pr: none

# pr:
#   branches:
#     include:
#     - main

pool:
  vmImage: windows-latest

steps:
  - task: DownloadPackage@1
    inputs:
      packageType: 'nuget'
      feed: '/2a0f0189-f7d9-4fa6-850c-80a9a1307654'
      view: 'd98cc08c-815d-437f-a08c-b73af7136624'
      definition: 'dee6e24c-883e-442c-b0d3-23155c6536c6'
      version: '24.11.0-alpha-3366'
      extract: false
      downloadPath: '$(System.ArtifactsDirectory)'
  
  - task: UiPathInstallPlatform@4
    inputs:
      cliVersion: 'WIN_23.10.8894.39673'
      cliNupkgPath: '$(System.ArtifactsDirectory)\UiPath.CLI.Windows.nupkg'
  
  - task: UiPathPack@4
    inputs:
      versionType: 'AutoVersion'
      projectJsonPath: 'AutomationProjects/CrossPlatform/VB/SimpleLog_CrossPlatform_VB/project.json'
      orchestratorConnection: 'alpha-for-official'
      outputPath: '$(Build.ArtifactStagingDirectory)\Output'
      traceLevel: 'Information'
  
  - task: UiPathDeploy@4
    inputs:
      orchestratorConnection: 'alpha-for-official'
      packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
      folderName: 'AzureFolder'
      traceLevel: 'Information'