trigger: none
pr: none

# pr:
#   branches:
#     include:
#     - main

pool:
  vmImage: windows-latest

steps:
  - task: DownloadPackage@1
    inputs:
      packageType: 'nuget'
      feed: '03327aeb-cec9-448f-bdda-9ca558ee7f9c/c0a014d3-bb1e-4495-a89f-711e0d5e67fe'
      view: 'e159cfb8-8ced-4a5a-96f5-8dbe46b6cfdd'
      definition: 'f53f6c29-0f44-4fb5-96ea-794b815c5b39'
      version: '24.11.0-alpha.17354'
      extract: false
      downloadPath: '$(System.ArtifactsDirectory)'
  
  - task: UiPathInstallPlatform@4
    inputs:
      cliVersion: 'WIN_23.10.8894.39673'
      cliNupkgPath: '$(System.ArtifactsDirectory)\UiPath.CLI.Windows.nupkg'

  # - task: UiPathTest@4
  #   inputs:
  #     testTarget: 'TestProject'
  #     orchestratorConnection: 'stg CiPlugins'
  #     testProjectPath: 'AutomationProjects/CrossPlatform/VB/TestCase_CrossPlatform_VB/project.json'
  #     folderName: 'AzureFolder'
  #     traceLevel: 'Information'
  
  - task: UiPathPack@4
    inputs:
      versionType: 'AutoVersion'
      projectJsonPath: 'AutomationProjects/CrossPlatform/VB/TestCase_CrossPlatform_VB/project.json'
      orchestratorConnection: 'stg CiPlugins'
      outputPath: '$(Build.ArtifactStagingDirectory)\Output'
      traceLevel: 'Information'
  
  # - task: UiPathDeploy@4
  #   inputs:
  #     orchestratorConnection: 'stg CiPlugins'
  #     packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
  #     folderName: 'AzureFolder'
  #     traceLevel: 'Information'