trigger: none
pr: none

parameters:
  - name: testId
    displayName: 'testId'
    type: string
    default: '38'

pool:
  vmImage: windows-latest

steps:
  - powershell: |
      echo "##vso[task.setvariable variable=COVERED_TESTS]23,45,38,87"
    displayName: 'Set Mock COVERED_TESTS Environment Variable'
  
  - powershell: |
      $coveredTests = "$(COVERED_TESTS)".Split(',')
      $shouldRun = $coveredTests -contains "${{ parameters.testId }}"
      echo "##vso[task.setvariable variable=ShouldRunTask]$shouldRun"
    displayName: 'Set ShouldRunTask Variable'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['ShouldRunTask'], 'True'))
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Hello World"