trigger: none
pr: none

# pr:
#   branches:
#     include:
#     - main

pool:
  vmImage: windows-latest

steps:
  - task: DownloadPackage@1
    inputs:
      packageType: 'nuget'
      feed: '/dcd1e333-0124-49de-ba88-1a9997f883b1'
      view: '44d13dae-d7b4-457f-b97e-ae45bdf2e7f9'
      definition: '5d1973e4-d8e0-42b9-8c06-beb25937dc4b'
      version: '23.10.8894.39673'
      extract: false
      downloadPath: '$(System.ArtifactsDirectory)'
  
  - task: UiPathInstallPlatform@4
    inputs:
      cliVersion: 'WIN_23.10.8894.39673'
      cliNupkgPath: '$(System.ArtifactsDirectory)\UiPath.CLI.Windows.nupkg'

  - task: UiPathTest@4
    inputs:
      testTarget: 'TestProject'
      orchestratorConnection: 'stg CiPlugins'
      testProjectPath: 'AutomationProjects/CrossPlatform/VB/DemoLibrary/project.json'
      folderName: 'AzureFolder'
      traceLevel: 'Information'
  
  - task: UiPathPack@4
    inputs:
      versionType: 'AutoVersion'
      projectJsonPath: 'AutomationProjects/CrossPlatform/VB/DemoLibrary/project.json'
      orchestratorConnection: 'stg CiPlugins'
      outputPath: '$(Build.ArtifactStagingDirectory)\Output'
      traceLevel: 'Information'
  
  - task: UiPathDeploy@4
    inputs:
      orchestratorConnection: 'stg CiPlugins'
      packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
      folderName: 'AzureFolder'
      traceLevel: 'Information'
  
  - task: UiPathAssets@4
    inputs:
      orchestratorConnection: 'stg CiPlugins'
      folderName: 'AzureFolder'
      assetActionType: 'Deploy'
      csvFile: 'Assets/assests.csv'
      traceLevel: 'Information'

  - task: UiPathRunJob@4
    inputs:
      orchestratorConnection: 'stg CiPlugins'
      processName: 'DemoProcess'
      folderName: 'AzureFolder'
      traceLevel: 'Information'