# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: Demo
  jobs:
    - job: Demo
      steps:
        - task: UiPathInstallPlatform@4
          inputs:
            cliVersion: 'WIN_23.10.8753.32995'
        
        - task: UseDotNet@2
          inputs:
            packageType: 'runtime'
            version: '6.0.302'
        
        - task: UiPathPack@4
          inputs:
            versionType: 'AutoVersion'
            projectJsonPath: '/path/to/project.json'
            orchestratorConnection: 'CI Plugins connection'
            outputPath: '$(Build.ArtifactStagingDirectory)\Output'
            traceLevel: 'Information'